### ISSUE TITLE
Add range match to sortdb

### ISSUE THREAD

**Issue by noam-c** [jehiah/sortdb#2]
My team at Moz is planning on using sortdb to hold data indexed by timestamps. We'd like to create an API endpoint to allow range matching between one key and another, based on the existing sorting of the keys:

```
/range?start=key1&end=key2...
```

Some examples:

For the DB with these keys:

```
b
bb
c
cc
f
```

| Input | Expected records | Comments |
| --- | --- | --- |
| `/range?start=bb&end=d` | bb, c, cc | Standard use case. |
| `/range?start=a&end=cc` | b, bb, c, cc | If the start key precedes the first key in the db, gets all records until the end key. |
| `/range?start=a&end=c` | b, bb, c | Note the expectation here compared to the last call: this will not use prefix match as `fwmatch` does, in order to avoid confusion about which keys are retrieved. |
| `/range?start=c&end=z` | c, cc, f | If the end key is out of range, gets all records from the first match to the start key onward. |
| `/range?start=g&end=z` | 404 Error: NOT_FOUND | As expected, nothing is returned if there is no key found in that range. |
| `/range?start=z&end=a` | 400 Error: MALFORMED_RANGE | Error is returned if `end` comes before `start` in sort order. |

Note that for ease of reading, I didn't include records or delimit the keys with newlines. In reality, the expected output format would be the same as expected for `fwmatch`.

We'd particularly find this handy for our use case (since we could then pick out data corresponding to a range of dates), but we also believe it'll be a useful endpoint to add in general since clients of sortdb will naturally take advantage of the sorted nature of the DB when choosing their keys. Since the data is retrieved sequentially, range match can (and should) be a fast operation.

I plan to implement this in the Go version of sortdb, but I'd also like to add it to the C version if that's still in active use and development. In either case, I wanted to open up this issue first so that any questions or concerns about the endpoint can be ironed out first. Please let me know if you have any feedback on this before I proceed. Thank you!

**Comment by jehiah** [comment]
@noam-c I think this is great. I look forward to seeing this patch and can think of ways i could take advantage of it as well.

Your example has `start` be inclusive of a match, but `end` be exclusive of a match. I think that's confusing and both should be inclusive. I think generally speaking if you know the end record you want, it requires more brainpower than i'd want to use to figure out what the next lexical key would be to actually get that record back.

I imagine the scenario you might be thinking of w/ timestamps where you would want exlusive end match is if you do say `start=20150101` and `end=20150201` but you really want just up to and including `end=20150131`. Is that what you were thinking? Is there a clear way we can have different end value parameters that makes it clear which type of request you wanted so we could support both?

**Comment by noam-c** [comment]
@jehiah The scenario has more to do with hashes being appended to the timestamps in our use case. If we specify a start timestamp without a hash, then the range match will still start at the right place. But if we similarly specified the end key without a hash, then it wouldn't match the last key that we want. We also played with the idea of making the two keys prefix match, like `fwmatch`, but the semantics were even more confusing. That's how we ended up landing on exclusive match at the end.

That being said, I agree that that makes it more confusing and also perhaps less generic. In addition, we can just increment the timestamp for our use case and everything would still work. And it would make this endpoint far less confusing. So let's go with your suggestion and make it inclusive on both ends. I'll update the issue description for posterity. :+1:

**Comment by noam-c** [comment]
Hello! Just circling back because it's been a little while. This is still definitely on our radar, but unfortunately something urgent came up that we need to finish before I can devote time to this. I'm very sorry for the delay and for the lack of communication on my part; I'm still looking forward to digging into this in earnest in a couple of weeks.

**Comment by noam-c** [comment]
One tweak that I've made here is that I'm choosing to return a MALFORMED_RANGE (400) error if `end < start`. @jehiah feel free to push back on that if you feel that the response be 200 with an empty set.

**Comment by noam-c** [comment]
Oh, and the empty set case (if the range matches nothing) returns a 404 (NOT_FOUND) just as the other endpoints do.

**Comment by jehiah** [comment]
@noam-c both those details sound good to me
