### ISSUE TITLE
db.Search doesn't actually create a copy as described

### ISSUE THREAD

**Issue by noam-c** [jehiah/sortdb#4]
This was discovered during work on issue #2.
At the end of a search, in order to avoid a race condition modifying the data prior to its return, a copy is intentionally made [here](https://github.com/jehiah/sortdb/blob/master/sorted_db/db.go#L179).
Unfortunately, the operator used on line 180 (`[]byte(db.data...)`) is just a redundant cast operator on the slice. The slice itself is, of course, referencing the same memory as db.data. So no copy is actually created and the race condition still exists.
This can be fixed by either using `make` and `copy` or by `append`ing the results to an empty slice.

**Comment by noam-c** [comment]
Thanks to @TheDahv for helping me discover this one. We know the right fix here and we will send a PR soon. :)

**Comment by jehiah** [comment]
Thanks for uncovering this! Nice detective work @noam-c and @TheDahv
